# Generated by Django 5.0 on 2024-01-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_teacher_age_alter_teacher_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='age',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='designation',
            field=models.CharField(default='software developer', max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(default='shahid', max_length=50),
        ),
    ]
