# Generated by Django 5.0 on 2024-01-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_teacher_age_alter_teacher_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='age',
            field=models.IntegerField(default=30, null=True),
        ),
    ]
