# Generated by Django 5.0 on 2024-01-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_teacher_age_alter_teacher_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='designation',
            field=models.CharField(default='Patel', max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(default='Shahid', max_length=50),
        ),
    ]
