# Generated by Django 5.0 on 2024-01-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_teacher_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='age',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='designation',
            field=models.CharField(max_length=50),
        ),
    ]
