# Generated by Django 5.0 on 2024-01-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_teacher_age_alter_teacher_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='age',
            field=models.IntegerField(default=155),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='designation',
            field=models.CharField(default='senior madarchod', max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(default='sanjay', max_length=50),
        ),
    ]
